-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/ChangePrimaryKey.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE openid_connect
  DROP CONSTRAINT openid_connect_pkey;
ALTER TABLE openid_connect
  ADD oidc_id SERIAL NOT NULL;
ALTER TABLE openid_connect
  ADD PRIMARY KEY (oidc_id);
