-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: ChangePrimaryKey.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
DROP  INDEX "primary";
ALTER TABLE  openid_connect
ADD  oidc_id SERIAL NOT NULL;
ALTER TABLE  openid_connect
ADD  PRIMARY KEY (oidc_id);