-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: OpenIDConnect.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE openid_connect (
  oidc_user INT NOT NULL,
  oidc_subject TEXT NOT NULL,
  oidc_issuer TEXT NOT NULL,
  PRIMARY KEY(oidc_user)
);

CREATE INDEX openid_connect_subject ON openid_connect (oidc_subject, oidc_issuer);
