-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: OpenIDConnect.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/openid_connect (
  oidc_user INTEGER UNSIGNED NOT NULL,
  oidc_subject BLOB NOT NULL,
  oidc_issuer BLOB NOT NULL,
  PRIMARY KEY(oidc_user)
);

CREATE INDEX openid_connect_subject ON /*_*/openid_connect (oidc_subject, oidc_issuer);
