-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: sql/ChangePrimaryKey.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE /*_*/openid_connect
  ADD oidc_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  DROP PRIMARY KEY,
  ADD PRIMARY KEY (oidc_id);
