-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: OpenIDConnect.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/openid_connect (
  oidc_user INT UNSIGNED NOT NULL,
  oidc_subject TINYBLOB NOT NULL,
  oidc_issuer TINYBLOB NOT NULL,
  INDEX openid_connect_subject (
    oidc_subject(50),
    oidc_issuer(50)
  ),
  PRIMARY KEY(oidc_user)
) /*$wgDBTableOptions*/;
